---
# role: kickstart
# file: molecule/fedora/molecule.yml

dependency:
  name: "galaxy"
driver:
  name: "podman"
provisioner:
  name: "ansible"
  config_options:
    defaults:
      forks: 8
      interpreter_python: "auto_silent"
      allow_world_readable_tmpfiles: true
      callbacks_enabled: "ansible.posix.profile_tasks,ansible.posix.timer"
      callback_result_format: "yaml"
      remote_tmp: "/tmp/.ansible/tmp"
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    converge: "../resources/playbooks/converge.yml"
    verify: "../resources/playbooks/verify.yml"
  inventory:
    host_vars:
      kickstart-almalinux:
        kickstart_files:
          - dest: "/tmp/kickstart-almalinux.ks"
            distribution: "AlmaLinux"
            distribution_major_version: "10"
            hardware: "amd"
            networks:
              - "network --bootproto=dhcp --hostname=almalinux.kickstart.test"
        __kickstart_test_expected:
          - "zerombr"
          - "--append=\"amd_iommu=force_isolation mitigations=auto"
          - "--excludedocs"
          - "python3-dnf"
          - "python3-virt-firmware"
          - "tpm2-tools"
          - "amd-gpu-firmware"
          - "--hostname=almalinux.kickstart.test"
          - "rootpw --lock"
          - "sshkey --username=root"
          - "ks-post-disable-coredumps.log"
          - "ks-post-modprobe-blacklist-drivers.log"
          - "ks-post-modprobe-blacklist-fs.log"
          - "ks-post-modprobe-blacklist-net.log"
          - "ks-post-harden-sysctl-net-ipv4.log"
          - "ks-post-harden-sysctl-net-ipv6.log"
          - "ks-post-harden-sysctl.log"
          - "ks-post-systemd-disable-sleep.log"
          - "systemctl mask sleep.target"
        __kickstart_test_unexpected:
          - "qemu-guest-agent"
          - "intel-gpu-firmware"
          - "python3-libdnf5"
      kickstart-fedora:
        kickstart_files:
          - dest: "/tmp/kickstart-fedora.ks"
            distribution: "Fedora"
            distribution_major_version: "44"
            kernel_cmdline:
              - "console=ttyS0"
            post_scripts:
              systemd-disable-sleep: false
            networks:
              - "network --bootproto=dhcp --hostname=fedora.kickstart.test"
        __kickstart_test_expected:
          - "zerombr"
          - "--append=\"mitigations=auto"
          - "vsyscall=none console=ttyS0\""
          - "--excludedocs"
          - "qemu-guest-agent"
          - "-amd-gpu-firmware"
          - "-intel-gpu-firmware"
          - "python3-libdnf5"
          - "vim-default-editor"
          - "--hostname=fedora.kickstart.test"
          - "rootpw --lock"
          - "sshkey --username=root"
          - "ks-post-harden-sysctl.log"
        __kickstart_test_unexpected:
          - "ks-post-systemd-disable-sleep.log"
          - "python3-dnf"
          - "python3-virt-firmware"
          - "tpm2-tools"
verifier:
  name: "ansible"
scenario:
  name: "fedora"
platforms:
  - pre_build_image: true
    override_command: false
    systemd: "true"
    name: "kickstart-fedora"
    image: "docker.io/${uns:-jomrr}/molecule-fedora:latest"
