---
# code: language=ansible
# role: jomrr.kickstart
# file: tasks/main.yml

- name: "Install pykickstart"
  become: true
  ansible.builtin.dnf:
    name: pykickstart
    state: present

- name: "Create kickstart file"
  become: false
  ansible.builtin.template:
    src: kickstart.cfg.j2
    dest: "{{ ks.dest }}"
    mode: '0660'
    validate: ksvalidator --version={{ ks.version }} %s
  vars:
    ks: "{{ kickstart_defaults | combine(item, recursive=True) }}"
  loop: "{{ kickstart_files }}"
