---
# role: kickstart
# file: tasks/main.yml

- name: KICKSTART | Install pykickstart
  become: true
  become_user: root
  ansible.builtin.package:
    name: pykickstart
    state: present

- name: KICKSTART | Create kickstart files
  ansible.builtin.include_tasks: file.yml
  loop: "{{ kickstart_files }}"
  loop_control:
    loop_var: __kickstart_item
    label: "{{ __kickstart_item.dest }}"
