---
# role: kickstart
# file: tasks/main.yml

- name: KICKSTART | Gather distribution and home directory of the executing host
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution
      - user
    filter:
      - ansible_distribution
      - ansible_user_dir
  delegate_facts: true
  register: __kickstart_host

- name: KICKSTART | Install pykickstart
  become: true
  become_user: root
  ansible.builtin.package:
    name: pykickstart
    state: present
  when: kickstart_install

- name: KICKSTART | Create kickstart files
  ansible.builtin.include_tasks: file.yml
  loop: "{{ kickstart_files }}"
  loop_control:
    loop_var: __kickstart_item
    label: "{{ __kickstart_item.dest }}"
