---
# role: kickstart
# file: molecule/resources/playbooks/converge.yml

- name: KICKSTART | Converge without play facts
  hosts: all
  gather_facts: false
  roles:
    - role: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
